services:
  api-products:
    container_name: ecom_ccvmt_prod_api_products
    build:
      context: ./nest
      dockerfile: ./apps/products/Dockerfile
      target: production
    environment:
      PORT: 3000
      RABBIT_MQ_URI: ${RABBIT_MQ_URI}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      ORIGIN: ${ORIGIN}
    depends_on:
      - mongo-primary
      - rabbitmq
    ports:
      - 3001:3000

  api-users:
    container_name: ecom_ccvmt_prod_api_users
    build:
      context: ./nest
      dockerfile: ./apps/users/Dockerfile
      target: production
    environment:
      PORT: 3000
      RABBIT_MQ_URI: ${RABBIT_MQ_URI}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      ORIGIN: ${ORIGIN}
    depends_on:
      - mongo-primary
      - rabbitmq
    ports:
      - 3002:3000

  api-auth:
    container_name: ecom_ccvmt_prod_api_auth
    build:
      context: ./nest
      dockerfile: ./apps/auth/Dockerfile
      target: production
    environment:
      PORT: 3000
      RABBIT_MQ_URI: ${RABBIT_MQ_URI}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_SECRET: ${JWT_SECRET}
      ORIGIN: ${ORIGIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
    depends_on:
      - mongo-primary
      - rabbitmq
    ports:
      - 3003:3000

  api-orders:
    container_name: ecom_ccvmt_prod_api_orders
    build:
      context: ./nest
      dockerfile: ./apps/orders/Dockerfile
      target: production
    environment:
      PORT: 3000
      RABBIT_MQ_URI: ${RABBIT_MQ_URI}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      ORIGIN: ${ORIGIN}
    depends_on:
      - mongo-primary
    ports:
      - 3004:3000

  api-categories:
    container_name: ecom_ccvmt_prod_api_categories
    build:
      context: ./nest
      dockerfile: ./apps/categories/Dockerfile
      target: production
    environment:
      PORT: 3000
      RABBIT_MQ_URI: ${RABBIT_MQ_URI}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      ORIGIN: ${ORIGIN}
    depends_on:
      - mongo-primary
    ports:
      - 3005:3000

  rabbitmq:
    container_name: ecom_ccvmt_prod_rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  mongo-primary:
    container_name: ecom_ccvmt_prod_mongo_primary
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - 'mongodb_prod_data:/data/db'
    ports:
      - 27018:27017

  reverse-proxy:
    container_name: ecom_ccvmt_prod_reverse_proxy
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.production.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-products
      - api-users
      - api-auth
      - api-orders
      - api-categories

  thumbor:
    container_name: ecom_ccvmt_prod_thumbor
    image: minimalcompact/thumbor:latest
    environment:
      THUMBOR_NUM_PROCESSES: 8
      LOADER: thumbor.loaders.file_loader
    volumes:
      - ./data:/data/loader
    ports:
      - 8888:80

volumes:
  mongodb_prod_data:
    driver: local
